# Site settings
title: TileFusion
description: TileFusion is a highly efficient C++ macro kernel template library designed to elevate the level of abstraction in CUDA C for processing tiles.
baseurl: "/tilefusion-docs"
url: "https://tiledtensor.github.io/tilefusion-docs/"
authors:
  - name: "Ying Cao"
    email: "lcy.seso@gmail.com"
    github: "lcy-seso"
  - name: "Chengxiang Qi"
    email: "KuangjuX@outlook.com"
    github: "KuangjuX"

mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-mml-chtml"
  tags:  "none" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/microsoft/TileFusion" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - docs/index.md
  - docs/installation.md
  - docs/design/index.md
  - docs/examples/index.md
  - docs/benchmarks/index.md
  - docs/about.md

# Just the Docs configuration
aux_links:
  "TileFusion on GitHub":
    - "//github.com/microsoft/TileFusion"
